### ISSUE TITLE
[Bug] ConvexHullTrickAddMonotone

### ISSUE THREAD

**Issue by goodstudyqaq** [ei1333/library#139]
Hi, there is a bug in [ConvexHullTrickAddMonotone](https://github.com/ei1333/library/blob/master/structure/convex-hull-trick/convex-hull-trick-add-monotone.hpp). 

The `check` function will return `ab * bc >= 0` and it uses division to avoid data overflow. But for integers, it cannot be easy just to use division to compare because it will be rounded down. 

There is a small case to hack this [test](https://ei1333.github.io/library/test/verify/yosupo-line-add-get-min-2.test.cpp)
`
5 1
9 0
6 2
5 -2
-9 0
-6 8
1 0
`

The test will return 0. However, the answer is -2.

This is my implementation:
```cpp
    bool check(const Data &a, const Data &b, const Data &c) {
        // return (b.F-a.F)*(c.S-b.S) >= (b.S-a.S)*(c.F-b.F); return ab * bc >= 0
        if (b.first == a.first || c.first == b.first) {
            return sgn(b.first - a.first) * sgn(c.second - b.second) >= sgn(c.first - b.first) * (b.second - a.second);
        }
        // return (b.second - a.second) / (a.first - b.first) >= (c.second - b.second) / (b.first - c.first);

        Data ab = b - a;
        Data bc = c - b;

        if (sgn(ab.first) * sgn(bc.second) != sgn(ab.second) * sgn(bc.first)) {
            return sgn(ab.first) * sgn(bc.second) >= sgn(ab.second) * sgn(bc.first);
        }

        Data left = {bc.second / bc.first, bc.second % bc.first};
        Data right = {ab.second / ab.first, ab.second % ab.first};

        if (left.first != right.first) {
            return left.first >= right.first;
        }

        return left.second * ab.first >= right.second * bc.first;
    }
```

**Comment by goodstudyqaq** [comment]
I think the check function may not be very common. Because I also use multiply in the last line, and it may be overflows.

**Comment by ei1333** [comment]
Thank you for reporting this. Maybe we need to use the floor function rather than truncation 🙇‍♂️

**Comment by goodstudyqaq** [comment]
> Thank you for reporting this. Maybe we need to use the floor function rather than truncation 🙇‍♂️ https://noshi91.hatenablog.com/entry/2021/03/23/200810

Thank you. This article is helpful for me.
