### ISSUE TITLE
geometry/angle.cpp の get_smaller_angle がバグっている気がします。

### ISSUE THREAD

**Issue by jupiro** [ei1333/library#25]
https://github.com/ei1333/library/blob/dacf25d46340901ff7e9a3f2e6fa1ccc69952a8a/geometry/angle.cpp#L14

なんですが、`v(a-b)` な気がしています。

**Comment by jupiro** [comment]
バグっているような気がしますので、修正しました。

**Comment by ei1333** [comment]
ありがと
