### ISSUE TITLE
local.toml　くれ

### ISSUE THREAD

**Issue by Luzhiled** [ei1333/library#36]
[参考](https://github.com/beet-aizu/library/blob/master/.verify-helper/local.toml)

`#include <bits/stdc++.h>` されているのでローカルでテストを回すと落ちます

`./verify-helper` 下に `local.toml` などを作って gcc だけ書いて 

`oj-verify --config-file ./.verify-helper/local.toml run`

とでもやればローカルでも verify 可能なので、くれ

**Comment by ei1333** [comment]
あげない
