### ISSUE TITLE
dmoj-ds5.test.cpp のテスト

### ISSUE THREAD

**Issue by Luzhiled** [ei1333/library#43]
[大先生がCC0-1.0 Licenseで公開してくださっておりました](https://github.com/bqi343/USACO/blob/4aa96cd195a770c3a7f8977441020036d84b4f24/Implementations/content/graphs%20(12)/Advanced/DMOJdynamicTreeTest.cpp)、generator なりを書いて hello world を指定して単体テストを実行などの形式に変えてもよろしいでしょうか

_Originally posted by @Luzhiled in https://github.com/ei1333/library/discussions/42#discussioncomment-1533815_

**Comment by Luzhiled** [comment]
とりあえず ignore したほうがよかったりしますか　よろしくお願いします

**Comment by ei1333** [comment]
ありがとうございます

**Comment by ei1333** [comment]
これおわってますね
