### ISSUE TITLE
テストケース落ちまくり

### ISSUE THREAD

**Issue by ei1333** [ei1333/library#72]
なおしてくれ

**Comment by ei1333** [comment]
https://github.com/ei1333/library/blob/096efd1b7e61f2bf9df058778df14c30d988903a/test/verify/yosupo-pow-of-formal-power-series.test.cpp が悪さをしてそう？

**Comment by Luzhiled** [comment]
話を聞けや
https://github.com/ei1333/library/pull/68

**Comment by ei1333** [comment]
@Luzhiled よろしく！
