### ISSUE TITLE
convex_polygon_contains のバグ

### ISSUE THREAD

**Issue by ei1333** [ei1333/library#85]
https://twitter.com/kyopro_friends/status/1642165789666205697

https://github.com/ei1333/library/blob/c52725e8eadb97b38f26c1ef45fab39c485b27dc/geometry/convex_polygon_contains.hpp#L9

**Comment by beet-aizu** [comment]
#86

**Comment by beet-aizu** [comment]
すみません close を指定し忘れました

**Comment by ei1333** [comment]
#85 close

**Comment by ei1333** [comment]
とじてなかった
